local assert = require("luassert")
local FilterOpts = require("vault.filter_opts")
-- stdpath

describe("VaultNotesFilterOpts", function()
  -- add stdpath to be recognized by plenary busted
  vim.g.stdpath = vim.fn.stdpath("config")
  it("should return a new NotesFilterOpts object", function()
    local opts = FilterOpts({ "tags", { "foo", "bar" }, { "baz" }, "exact", "all" })
    assert.is_true(opts.include[1] == "foo")
    assert.is_true(opts.include[2] == "bar")
    assert.is_true(opts.exclude[1] == "baz")
    assert.is_true(opts.match_opt == "exact")
    assert.is_true(opts.mode == "all")
  end)
  it("should not return a new NotesFilterOpts object", function()
    local opts = FilterOpts({ "tags", { "foo", "bar" }, { "baz" }, "exact", "all" })
    assert.is_false(opts.include[1] == "foobar")
    assert.is_false(opts.include[2] == "barbuzz")
    assert.is_false(opts.exclude[1] == "foobarbuzz")
    assert.is_false(opts.match_opt == "startswith")
    assert.is_false(opts.mode == "any")
  end)
end)
