
--
-- --- Picker for browsing tags from root tag.
-- --- For example we have tag: status/TODO/later
-- --- We want to browse it like this:
-- --- status
-- --- status/TODO
-- --- status/TODO/later
-- --- And then pick we open notes picker filtered by tag: status/TODO/later
-- --- @param root_tag_name? string - Root tag to start browsing from
--- @return Picker
-- function vault_pickers.root_tags(root_tag_name)
--     local root_dir = config.options.root
--     local tags = {}
--     if root_tag_name ~= nil then
--         tags = Tags():filter(root_tag_name)
--     else
--         tags = Tags()
--     end
--
--     if next(tags) == nil then
--         Log.info("No root tags found in vault: " .. root_dir)
--         return
--     end
--
--     local root_tags = {}
--     local seen_root_tags = {}
--     for _, tag in ipairs(tags) do
--         local _root_tag_name = tag.name:match("([^/]+)")
--         if not seen_root_tags[_root_tag_name] then
--             seen_root_tags[_root_tag_name] = true
--             table.insert(root_tags, _root_tag_name)
--         end
--     end
--
--     local make_display = function(entry)
--         local entry_width = 29
--         local displayer = entry_display.create({
--             separator = " ",
--             items = {
--                 { width = entry_width },
--                 { remaining = true },
--             },
--         })
--         local tag_name = entry.name
--         return displayer({
--             { tag_name, "TelescopeResultsNormal" },
--         })
--     end
--
--     local entry_maker = function(tag)
--         return {
--             value = tag,
--             ordinal = tag,
--             display = make_display,
--         }
--     end
--
--     local function enter(bufnr)
--         local selection = actions_state.get_selected_entry()
--         local root_tag = selection.value
--         vault_pickers.root_tags(root_tag)
--         vault_actions.close(bufnr)
--     end
--
--     local picker = pickers
--         .new(vault_layouts.mini(), {
--             prompt_title = "Status",
--             finder = finders.new_table({
--                 results = root_tags,
--                 entry_maker = entry_maker,
--             }),
--             sorter = sorters.get_generic_fuzzy_sorter(),
--             attach_mappings = function(_, _)
--                 actions.select_default:replace(enter)
--                 return true
--             end,
--         })
--         :find()
--     vault_state.set_global_key("picker", picker)
--     return picker
-- end
